Update virtualbox to version 7.2.8 / rev 308 via SR 1359115
https://build.opensuse.org/request/show/1359115
by user jengelh + anag_factory
- Update to release 7.2.8

diff --git a/packages/v/virtualbox/vbox-vboxdrv-init-script.diff b/packages/v/virtualbox/vbox-vboxdrv-init-script.diff
--- a/packages/v/virtualbox/vbox-vboxdrv-init-script.diff
+++ b/packages/v/virtualbox/vbox-vboxdrv-init-script.diff
@@ -1,21 +1,20 @@
 ---
- src/VBox/Installer/linux/vboxdrv.sh |   42 ++++++------------------------------
- 1 file changed, 7 insertions(+), 35 deletions(-)
+ src/VBox/Installer/linux/vboxdrv.sh |   52 ++++--------------------------------
+ 1 file changed, 6 insertions(+), 46 deletions(-)
 
-Index: VirtualBox-7.1.0/src/VBox/Installer/linux/vboxdrv.sh
+Index: VirtualBox-7.2.8/src/VBox/Installer/linux/vboxdrv.sh
 ===================================================================
---- VirtualBox-7.1.0.orig/src/VBox/Installer/linux/vboxdrv.sh
-+++ VirtualBox-7.1.0/src/VBox/Installer/linux/vboxdrv.sh
+--- VirtualBox-7.2.8.orig/src/VBox/Installer/linux/vboxdrv.sh
++++ VirtualBox-7.2.8/src/VBox/Installer/linux/vboxdrv.sh
 @@ -29,11 +29,12 @@
  #
  ### BEGIN INIT INFO
  # Provides:       vboxdrv
 -# Required-Start: $syslog
 -# Required-Stop:
--# Default-Start:  2 3 4 5
 +# Required-Start: $syslog $remote_fs
 +# Required-Stop:  $syslog $remote_fs
-+# Default-Start:  2 3 5
+ # Default-Start:  2 3 4 5
  # Default-Stop:   0 1 6
 -# Short-Description: VirtualBox Linux kernel module
 +# Short-Description: VirtualBox Linux module
@@ -23,7 +22,7 @@ Index: VirtualBox-7.1.0/src/VBox/Installer/linux/vboxdrv.sh
  ### END INIT INFO
  
  ## @todo This file duplicates a lot of script with vboxadd.sh.  When making
-@@ -571,13 +572,6 @@ See the documentation for your Linux dis
+@@ -573,13 +574,6 @@ See the documentation for your Linux dis
          fi
      fi
      # ensure permissions
@@ -37,14 +36,25 @@ Index: VirtualBox-7.1.0/src/VBox/Installer/linux/vboxdrv.sh
      if ! $MODPROBE vboxnetflt > /dev/null 2>&1; then
          failure "modprobe vboxnetflt failed. Please use 'dmesg' to find out why"
      fi
-@@ -736,30 +730,8 @@ setup()
+@@ -730,42 +724,8 @@ setup()
          module_build_log "$myerr"
          failure "Look at $LOG to find out what went wrong"
      fi
+-    log "Building the net filter module."
+-    if ! myerr=`$BUILDINTMP \
+-        --use-module-symvers /tmp/vboxdrv-Module.symvers \
+-        --module-source "$MODULE_SRC/vboxnetflt" \
+-        --skip-depmod \
+-        --no-print-directory install 2>&1`; then
+-        log "Error building the module:"
+-        module_build_log "$myerr"
+-        failure "Look at $LOG to find out what went wrong"
+-    fi
 -    log "Building the net adapter module."
 -    if ! myerr=`$BUILDINTMP \
 -        --use-module-symvers /tmp/vboxdrv-Module.symvers \
 -        --module-source "$MODULE_SRC/vboxnetadp" \
+-        --skip-depmod \
 -        --no-print-directory install 2>&1`; then
 -        log "Error building the module:"
 -        module_build_log "$myerr"
@@ -55,6 +65,7 @@ Index: VirtualBox-7.1.0/src/VBox/Installer/linux/vboxdrv.sh
 -        if ! myerr=`$BUILDINTMP \
 -            --use-module-symvers /tmp/vboxdrv-Module.symvers \
 -            --module-source "$MODULE_SRC/vboxpci" \
+-            --skip-depmod \
 -            --no-print-directory install 2>&1`; then
 -            log "Error building the module:"
 -            module_build_log "$myerr"
