Update virtualbox to rev 189 via SR 766683
https://build.opensuse.org/request/show/766683
by user lwfinger + dimstar_suse

diff --git a/packages/v/virtualbox/vbox-vboxdrv-init-script.diff b/packages/v/virtualbox/vbox-vboxdrv-init-script.diff
--- a/packages/v/virtualbox/vbox-vboxdrv-init-script.diff
+++ b/packages/v/virtualbox/vbox-vboxdrv-init-script.diff
@@ -1,7 +1,7 @@
-Index: VirtualBox-6.0.10/src/VBox/Installer/linux/vboxdrv.sh
+Index: VirtualBox-6.1.0_RC1/src/VBox/Installer/linux/vboxdrv.sh
 ===================================================================
---- VirtualBox-6.0.10.orig/src/VBox/Installer/linux/vboxdrv.sh
-+++ VirtualBox-6.0.10/src/VBox/Installer/linux/vboxdrv.sh
+--- VirtualBox-6.1.0_RC1.orig/src/VBox/Installer/linux/vboxdrv.sh
++++ VirtualBox-6.1.0_RC1/src/VBox/Installer/linux/vboxdrv.sh
 @@ -19,11 +19,12 @@
  #
  ### BEGIN INIT INFO
@@ -19,7 +19,7 @@ Index: VirtualBox-6.0.10/src/VBox/Installer/linux/vboxdrv.sh
  ### END INIT INFO
  
  ## @todo This file duplicates a lot of script with vboxadd.sh.  When making
-@@ -312,13 +313,6 @@ See the documenatation for your Linux di
+@@ -315,13 +316,6 @@ See the documenatation for your Linux di
          fi
      fi
      # ensure permissions
@@ -33,7 +33,7 @@ Index: VirtualBox-6.0.10/src/VBox/Installer/linux/vboxdrv.sh
      if ! $MODPROBE vboxnetflt > /dev/null 2>&1; then
          failure "modprobe vboxnetflt failed. Please use 'dmesg' to find out why"
      fi
-@@ -448,48 +442,8 @@ cleanup()
+@@ -451,50 +445,8 @@ cleanup()
  # setup_script
  setup()
  {
@@ -66,14 +66,16 @@ Index: VirtualBox-6.0.10/src/VBox/Installer/linux/vboxdrv.sh
 -        module_build_log "$myerr"
 -        failure "Look at $LOG to find out what went wrong"
 -    fi
--    log "Building the PCI pass-through module."
--    if ! myerr=`$BUILDINTMP \
--        --use-module-symvers /tmp/vboxdrv-Module.symvers \
--        --module-source "$MODULE_SRC/vboxpci" \
--        --no-print-directory install 2>&1`; then
--        log "Error building the module:"
--        module_build_log "$myerr"
--        failure "Look at $LOG to find out what went wrong"
+-    if test -e "$MODULE_SRC/vboxpci"; then
+-        log "Building the PCI pass-through module."
+-        if ! myerr=`$BUILDINTMP \
+-            --use-module-symvers /tmp/vboxdrv-Module.symvers \
+-            --module-source "$MODULE_SRC/vboxpci" \
+-            --no-print-directory install 2>&1`; then
+-            log "Error building the module:"
+-            module_build_log "$myerr"
+-            failure "Look at $LOG to find out what went wrong"
+-        fi
 -    fi
 -    rm -f /etc/vbox/module_not_compiled
 -    depmod -a
