Update systemd to version 246.6 / rev 319 via SR 846424
https://build.opensuse.org/request/show/846424
by user fbui + dimstar_suse

diff --git a/packages/s/systemd/systemd-sysv-convert b/packages/s/systemd/systemd-sysv-convert
--- a/packages/s/systemd/systemd-sysv-convert
+++ b/packages/s/systemd/systemd-sysv-convert
@@ -1,146 +1,112 @@
 #!/bin/bash
 
+info() {
+	echo "$(basename $0): $*"
+}
+
+warn() {
+	echo >&2 "$(basename $0): warning, $*"
+}
+
+usage() {
+	echo >&2 "usage: $(basename $0) --apply <service> [<service> ...]"
+}
+
 if [ "$UID" != "0" ]; then
-	echo Need to be root.
+	warn "need to be root, aborting"
 	exit 1
 fi
 
-declare -A results_target
-
-usage() {
-	cat << EOF
-usage: systemd-sysv-convert [-h] [--save] [--show] [--apply]
-                            SERVICE [SERVICE ...]
-EOF
-}
-
-help() {
+if [ $# -lt 2 ]; then
 	usage
-	cat << EOF
-Save and Restore SysV Service Runlevel Information
+	exit 1
+fi
 
-positional arguments:
-  SERVICE	Service names
+database_lookup() {
+	local service unused
 
-optional arguments:
-  -h, --help	show this help message and exit
-  --save	Save SysV runlevel information for one or more services
-  --show	Show saved SysV runlevel information for one or more services
-  --apply 	Apply saved SysV runlevel information for one or more services
-  		to systemd counterparts
-EOF
-}
-
-find_service() {
-	local service=$1
-	local rcnd=$2
-
-	case $rcnd in
-	boot.d)		[ -L /etc/rc.d/$rcnd/S??boot.$service ] ;;
-	*)		[ -L /etc/rc.d/$rcnd/S??$service ]
-	esac
-}
-
-lookup_database() {
-	local services=$@
-	local service
-	local runlevel
-	local priority
-
-	# 'priority' field is not used but is kept for backward compat
-	# reason.
-	while read service runlevel priority; do
-		for s in $services ; do
-			if [ $s == $service ]; then
-				results_target[$service]+=" runlevel$runlevel.target"
-				break
-			fi
-		done
-	done < /var/lib/systemd/sysv-convert/database
-}
-
-declare -i fail=0
-case "$1" in
-	-h|--help)
-		help
-		exit 0
-		;;
-	--save)
-		shift
-		for service in $@ ; do
-			if [ ! -r /etc/init.d/$service ] && [ ! -r /etc/init.d/boot.$service ]; then
-				echo "SysV service $service does not exist, skipping"
-				continue
-			fi
-			for rcnd in rc2.d rc3.d rc4.d rc5.d boot.d; do
-				case $rcnd in
-				rc*.d)	runlevel=${rcnd:2:1} ;;
-				boot.d)	runlevel=3 ;;
-				esac
-
-				# Write a dumb priority as it is not used.
-				find_service $service $rcnd &&
-				echo "$service	$runlevel 50" >>/var/lib/systemd/sysv-convert/database
-			done
-		done
-		;;
-	--show)
-		shift
-		services=$@
-		lookup_database $services
-		for service in $services; do
-  			if [ -z "${results_target[$service]}" ]; then
-				echo "No information about service $service found." >/dev/stderr
-				let fail++
-				continue
-			fi
-			for target in ${results_target[$service]}; do
-				echo "SysV service '$service' is pulled by $target"
-			done
-		done
-		;;
-	--apply)
-		shift
-		services=$@
-		for service in $services; do
-			if [ ! -f "/lib/systemd/system/$service.service" -a ! -f "/usr/lib/systemd/system/$service.service" ]; then
-				echo systemd service $service.service does not exist. >/dev/stderr
-				exit 1
-			fi
-		done
-
-		#
-		# The database might no have been created by a previous --save
-		# call. This can happen when:
-		#
-		#  - we're upgrading a package which initially didn't
-		#    have any unit file nor sysv init script and now
-		#    start shipping one or more unit files (bsc#982303).
-		#
-		#  - the sysv init service wasn't enabled at all before
-		#    being migrated to a native unit file (bsc#982211).
-		#
-		if [ -e /var/lib/systemd/sysv-convert/database ]; then
-			lookup_database $services
-			for service in $services; do
-				[ -f "/lib/systemd/system/$service.service" ] && unit="/lib/systemd/system/$service.service"
-				[ -f "/usr/lib/systemd/system/$service.service" ] && unit="/usr/lib/systemd/system/$service.service"
-
-				# If $service is not present in the database,
-				# then it simply means that the sysv init
-				# service was not enabled at all.
-				for target in ${results_target[$service]}; do
-					echo ln -sf $unit /etc/systemd/system/$target.wants/$service.service >/dev/stderr
-					mkdir -p "/etc/systemd/system/$target.wants"
-					/bin/ln -sf $unit /etc/systemd/system/$target.wants/$service.service
-				done
-			done
+	# 'priority' field is not used but is kept for backward compat reason.
+	while read service unused; do
+		if [ $service == $1 ]; then
+			return 0
 		fi
-		;;
-	*)
- 		usage
-		let fail=2
-		;;
-esac
+	done </var/lib/systemd/sysv-convert/database
 
-exit $fail
+	return 1
+}
+
+database_add() {
+	# Write a dumb priority as it is not used.
+	echo "$1	$2 50" >>/var/lib/systemd/sysv-convert/database
+}
+
+# Initialize the database.
+if [ ! -e /var/lib/systemd/sysv-convert/database ]; then
+	touch /var/lib/systemd/sysv-convert/database
+fi
+
+case "$1" in
+--save)
+	# --save is kept for backward compatibility.
+	;;
+--apply)
+	shift
+	for service in $@; do
+		# For backward compat we accept the name of the
+		# service with or without the unit type suffix. If the
+		# suffix is not there, assume .service type.
+		case "$service" in
+		*.*)	initscript="${service%.*}" ;;
+		*)	initscript="$service"
+			service="$service.service"
+		esac
+
+		# Did we already migrate this service during a previous update ?
+		database_lookup $initscript &&
+			continue
+
+		# Sanity check.
+		unit="/usr/lib/systemd/system/$service"
+		if [ ! -f "$unit" ]; then
+			warn "$unit not found, skipping"
+			continue
+		fi
+
+		# Mark the service as processed to make sure we will do the migration only
+		# once. This is important especially for packages that keep their init
+		# scripts around even if they're no more used. Since the saved info won't
+		# be reused again we simply use an invalid runlevel and add the service
+		# in the db only once.
+		database_add $initscript -1
+
+		# The package is introducing new services and never has any sysv init
+		# scripts (bsc#982303).
+		if [ ! -r /etc/init.d/$initscript ] &&
+		   [ ! -r /etc/init.d/boot.$initscript ]; then
+			continue
+		fi
+
+		for rcnd in rc2.d rc3.d rc4.d rc5.d boot.d; do
+			# Was the sysvinit script enabled ? (bsc#982211)
+			case $rcnd in
+			boot.d)	[ -L /etc/rc.d/boot.d/S??boot.$initscript ] || continue ;;
+			*)	[ -L /etc/rc.d/$rcnd/S??$initscript ] || continue
+			esac
+
+			case $rcnd in
+			boot.d)	runlevel=3 ;;
+			*)	runlevel=${rcnd:2:1}
+			esac
+
+			target=runlevel$runlevel.target
+			info "enabling $unit (wanted by $target)..."
+
+			mkdir -p "/etc/systemd/system/$target.wants"
+			ln -sf $unit /etc/systemd/system/$target.wants/$service
+		done
+	done
+	;;
+*)
+	usage
+	exit 1
+esac
