update 2023-11-29 22:10

diff --git a/packages/v/virt-manager/virt-manager-supportconfig b/packages/v/virt-manager/virt-manager-supportconfig
--- a/packages/v/virt-manager/virt-manager-supportconfig
+++ b/packages/v/virt-manager/virt-manager-supportconfig
@@ -3,50 +3,22 @@
 # Name:        Supportconfig Plugin for virt-manager
 # Description: Gathers important troubleshooting information
 #              about virt-manager
-# Author:      Jim Fehlig <jfehlig@suse.com>
 #############################################################
 
-RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
+RCFILE="/usr/lib/supportconfig/resources/supportconfig.rc"
+OF="output-virt-manager.txt"
 
 VIRTMAN_LOG_DIR="/root/.cache/virt-manager"
 VIRTMAN_LOG_FILES=""
 
 if [ -s $RCFILE ]; then
     if ! source $RCFILE; then
-        echo "ERROR: Initializing resource file: $RCFILE" >&2
+        log_write $OF "ERROR: Initializing resource file: $RCFILE"
         exit 1
     fi
 fi
 
-rpm_verify() {
-    thisrpm="$1"
-    local ret=0
+rpm_verify $OF virt-manager || exit 111
 
-    echo
-    echo "#==[ Validating RPM ]=================================#"
-    if rpm -q "$thisrpm" >/dev/null 2>&1; then
-        echo "# rpm -V $thisrpm"
-
-        if rpm -V "$thisrpm"; then
-            echo "Status: Passed"
-        else
-            echo "Status: WARNING"
-        fi
-    else
-        echo "package $thisrpm is not installed"
-	ret=1
-    fi
-    echo
-    return $ret
-}
-
-if ! rpm_verify virt-manager; then
-    echo "Skipped"
-    exit 0
-fi
-	
 test -d $VIRTMAN_LOG_DIR && VIRTMAN_LOG_FILES="$(find -L $VIRTMAN_LOG_DIR/ -type f)"
-plog_files 0 "$VIRTMAN_LOG_FILES"
-
-echo "Done"
-
+log_files $OF 0 "$VIRTMAN_LOG_FILES"
