Update nss-mdns to version 0.15.1 / rev 31 via SR 1319881
https://build.opensuse.org/request/show/1319881
by user dimstar + anag_factory
- Using nsswitch-config for setting nsswitch.conf
  (jsc#PED-13807)

diff --git a/packages/n/nss-mdns/nss-mdns-config b/packages/n/nss-mdns/nss-mdns-config
--- a/packages/n/nss-mdns/nss-mdns-config
+++ b/packages/n/nss-mdns/nss-mdns-config
@@ -2,7 +2,7 @@
 # vim: set ts=2 sw=2 et:
 
 #
-# Copyright (c) 2012, Novell, Inc.
+# Copyright (C) 2025 SUSE LLC
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -33,10 +33,10 @@
 # (Licensed under the simplified BSD license)
 #
 # Authors: Vincent Untz <vuntz@opensuse.org>
+#          Stefan Schubert <schubi@suse.com>
 #
 
-NSSWITCH=/etc/nsswitch.conf
-NSSWITCH_VENDOR=/usr/etc/nsswitch.conf
+ETC_NSSWITCH=/etc/nsswitch.conf
 
 usage() {
   echo "nss-mdns-config [--enable|--disable] [-4|-6] [--no-backup]"
@@ -79,23 +79,64 @@ if test "$IPv4" -ne 1 -a "$IPv6" -ne 1; then
   IPvALL=1
 fi
 
-if test ! -f "$NSSWITCH" && test ! -f "$NSSWITCH_VENDOR"; then
-  if test "$ENABLE" -ne 1 -a "$DISABLE" -ne 1; then
-    echo "No $NSSWITCH file."
-  fi
-  exit 0
+NSSWITCH_CONFIG_EXE="/bin/nsswitch-config"
+NSS_MDNS_ETC_FILE="/etc/nsswitch.conf.d/25-nss-mdns.conf"
+NSS_MDNS_ETC_FILE_IPV4="/etc/nsswitch.conf.d/25-nss-mdns-ipv4.conf"
+NSS_MDNS_ETC_FILE_IPV6="/etc/nsswitch.conf.d/25-nss-mdns-ipv6.conf"
+
+$NSSWITCH_CONFIG_EXE --is_generated >/dev/null 2>&1
+if [ "$?" -eq 0 ] ; then
+    if test "$ENABLE" -ne 1 -a "$DISABLE" -ne 1; then
+	# displaying status
+	if ! test -f $ETC_NSSWITCH; then
+	    echo "No $ETC_NSSWITCH has been found for information"
+	fi
+	if test -f "$NSS_MDNS_ETC_FILE"; then
+	    echo "Full support for nss-mdns is enabled."
+	elif test -f "$NSS_MDNS_ETC_FILE_IPV4"; then
+	    echo "Support for nss-mdns is enabled for IPv4."
+	elif test -f "$NSS_MDNS_ETC_FILE_IPV6"; then
+	    echo "Support for nss-mdns is enabled for IPv6."
+	else
+	    echo "Support for nss-mdns is disabled."	    
+	fi
+	exit 0
+    elif test "$DISABLE" -eq 1; then
+	# disabling
+	rm /etc/nsswitch.conf.d/25-nss-mdns* >/dev/null 2>&1
+    elif test "$ENABLE" -eq 1; then
+	# enabling
+	mkdir -p /etc/nsswitch.conf.d
+	rm /etc/nsswitch.conf.d/25-nss-mdns* >/dev/null 2>&1
+        if test "$IPvALL" -eq 1; then
+	  echo "# mdns_minimal has been generated by nss-mdns" >$NSS_MDNS_ETC_FILE
+          echo "hosts: mdns_minimal [NOTFOUND=return]" >>$NSS_MDNS_ETC_FILE
+        elif test "$IPv4" -eq 1; then
+	  echo "# mdns4_minimal has been generated by nss-mdns" >$NSS_MDNS_ETC_FILE_IPV4
+          echo "hosts: mdns4_minimal [NOTFOUND=return]" >>$NSS_MDNS_ETC_FILE_IPV4
+        elif test "$IPv6" -eq 1; then
+  	  echo "# mdns6_minimal has been generated by nss-mdns"  >$NSS_MDNS_ETC_FILE_IPV6	    
+          echo "hosts: mdns6_minimal [NOTFOUND=return]" >>$NSS_MDNS_ETC_FILE_IPV6
+        else
+          echo "Internal error when enabling."
+          exit 1
+        fi
+    fi
+    echo "Using $NSSWITCH_CONFIG_EXE for generating $ETC_NSSWITCH"    
+    exit $($NSSWITCH_CONFIG_EXE)
 fi
 
-if test ! -f "$NSSWITCH"; then
-  NSSWITCH_IN=$NSSWITCH_VENDOR
-else
-  NSSWITCH_IN=$NSSWITCH
-fi
+# Go on with this use case:
+# Updating /etc/nsswitch.conf which has been created manually or
+# by older releases.
+# ...
+# ..
+# .
 
-HOSTS=$(grep -m1 "^\s*hosts:" "$NSSWITCH_IN")
+HOSTS=$(grep -m1 "^\s*hosts:" "$ETC_NSSWITCH")
 
 if test $? -ne 0; then
-  echo "No hosts configuration in $NSSWITCH."
+  echo "No hosts configuration in $ETC_NSSWITCH."
   exit 0
 fi
 
@@ -107,6 +148,7 @@ if test "$ENABLE" -ne 1 -a "$DISABLE" -ne 1; then
   IPv6_ENABLED=0
   ENABLED=0
 
+  echo "Checking user changed $ETC_NSSWITCH."
   for ITEM in $VALUE; do
     if [ "$ITEM" = "mdns4_minimal" -o "$ITEM" = "mdns4" ]; then
       IPv4_ENABLED=1
@@ -161,13 +203,8 @@ elif test "$DISABLE" -eq 1; then
   done
 
   NEWVALUE=$(echo $NEWVALUE | sed "s/^\s*//;s/^\s*$//")
-
-  if test "$NSSWITCH_IN" = "$NSSWITCH_VENDOR"; then
-    cp -a "$NSSWITCH_IN" "$NSSWITCH"
-  elif test "$BACKUP" -eq 1; then
-    cp -a "$NSSWITCH" "${NSSWITCH}bak"
-  fi
-  sed -i "s/\(^\s*hosts:\s*\).*/\1$NEWVALUE/" "$NSSWITCH"
+  echo "Patching already existing $ETC_NSSWITCH."
+  sed -i "s/\(^\s*hosts:\s*\).*/\1$NEWVALUE/" "$ETC_NSSWITCH"
 
 elif test "$ENABLE" -eq 1; then
 
@@ -228,17 +265,16 @@ elif test "$ENABLE" -eq 1; then
   done
 
   if test "$FOUND_DNS" -ne 1; then
-    echo "No dns service for hosts configuration in $NSSWITCH."
+    echo "No dns service for hosts configuration in $ETC_NSSWITCH."
     exit 0
   fi
 
   NEWVALUE=$(echo $NEWVALUE | sed "s/^\s*//;s/^\s*$//")
 
-  if test "$NSSWITCH_IN" = "$NSSWITCH_VENDOR"; then
-    cp -a "$NSSWITCH_IN" "$NSSWITCH"
-  elif test "$BACKUP" -eq 1; then
-    cp -a "$NSSWITCH" "${NSSWITCH}bak"
+  if test "$BACKUP" -eq 1; then
+    cp -a "$ETC_NSSWITCH" "${ETC_NSSWITCH}bak"
   fi
-  sed -i "s/\(^\s*hosts:\s*\).*/\1$NEWVALUE/" "$NSSWITCH"
+  echo "Patching already existing $ETC_NSSWITCH."
+  sed -i "s/\(^\s*hosts:\s*\).*/\1$NEWVALUE/" "$ETC_NSSWITCH"
 
 fi
