Update go1.11 to rev 17 via SR 753318
https://build.opensuse.org/request/show/753318
by user dimstar_suse

diff --git a/packages/g/go1.11/gcc9-go.patch b/packages/g/go1.11/gcc9-go.patch
--- a/packages/g/go1.11/gcc9-go.patch
+++ b/packages/g/go1.11/gcc9-go.patch
@@ -7,7 +7,7 @@ Index: go/src/cmd/dist/buildtool.go
  	// or later we don't need to disable inlining to work around bugs in the Go 1.4 compiler.
  	cmd := []string{
 -		pathf("%s/bin/go", goroot_bootstrap),
-+		pathf("%s/bin/go-8", goroot_bootstrap),
++		pathf("%s/bin/go-9", goroot_bootstrap),
  		"install",
  		"-gcflags=-l",
  		"-tags=math_big_pure_go compiler_bootstrap",
@@ -20,7 +20,7 @@ Index: go/src/make.bash
  #
  # GOROOT_BOOTSTRAP: A working Go tree >= Go 1.4 for bootstrap.
 -# If $GOROOT_BOOTSTRAP/bin/go is missing, $(go env GOROOT) is
-+# If $GOROOT_BOOTSTRAP/bin/go-8 is missing, $(go env GOROOT) is
++# If $GOROOT_BOOTSTRAP/bin/go-9 is missing, $(go env GOROOT) is
  # tried for all "go" in $PATH. $HOME/go1.4 by default.
  
  set -e
@@ -30,8 +30,8 @@ Index: go/src/make.bash
  fi
 -if [ ! -x "$GOROOT_BOOTSTRAP/bin/go" ]; then
 -	echo "ERROR: Cannot find $GOROOT_BOOTSTRAP/bin/go." >&2
-+if [ ! -x "$GOROOT_BOOTSTRAP/bin/go-8" ]; then
-+	echo "ERROR: Cannot find $GOROOT_BOOTSTRAP/bin/go-8." >&2
++if [ ! -x "$GOROOT_BOOTSTRAP/bin/go-9" ]; then
++	echo "ERROR: Cannot find $GOROOT_BOOTSTRAP/bin/go-9." >&2
  	echo "Set \$GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4." >&2
  	exit 1
  fi
@@ -40,7 +40,7 @@ Index: go/src/make.bash
  fi
  rm -f cmd/dist/dist
 -GOROOT="$GOROOT_BOOTSTRAP" GOOS="" GOARCH="" "$GOROOT_BOOTSTRAP/bin/go" build -o cmd/dist/dist ./cmd/dist
-+GOROOT="$GOROOT_BOOTSTRAP" GOOS="" GOARCH="" "$GOROOT_BOOTSTRAP/bin/go-8" build -o cmd/dist/dist ./cmd/dist
++GOROOT="$GOROOT_BOOTSTRAP" GOOS="" GOARCH="" "$GOROOT_BOOTSTRAP/bin/go-9" build -o cmd/dist/dist ./cmd/dist
  
  # -e doesn't propagate out of eval, so check success by hand.
  eval $(./cmd/dist/dist env -p || echo FAIL=true)
@@ -53,7 +53,7 @@ Index: go/src/make.rc
  	GOROOT_BOOTSTRAP = $home/go1.4
  for(p in $path){
 -	if(! test -x $GOROOT_BOOTSTRAP/bin/go){
-+	if(! test -x $GOROOT_BOOTSTRAP/bin/go-8){
++	if(! test -x $GOROOT_BOOTSTRAP/bin/go-9){
  		if(go_exe = `{path=$p whatis go}){
  			goroot = `{GOROOT='' $go_exe env GOROOT}
  			if(! ~ $goroot $GOROOT){
@@ -62,7 +62,7 @@ Index: go/src/make.rc
  	}
  }
 -if(! test -x $GOROOT_BOOTSTRAP/bin/go){
-+if(! test -x $GOROOT_BOOTSTRAP/bin/go-8){
++if(! test -x $GOROOT_BOOTSTRAP/bin/go-9){
  	echo 'ERROR: Cannot find '$GOROOT_BOOTSTRAP'/bin/go.' >[1=2]
  	echo 'Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.' >[1=2]
  	exit bootstrap
@@ -71,7 +71,7 @@ Index: go/src/make.rc
  if(~ $#vflag 1)
  	echo cmd/dist
 -GOROOT=$GOROOT_BOOTSTRAP GOOS='' GOARCH='' $GOROOT_BOOTSTRAP/bin/go build -o cmd/dist/dist ./cmd/dist
-+GOROOT=$GOROOT_BOOTSTRAP GOOS='' GOARCH='' $GOROOT_BOOTSTRAP/bin/go-8 build -o cmd/dist/dist ./cmd/dist
++GOROOT=$GOROOT_BOOTSTRAP GOOS='' GOARCH='' $GOROOT_BOOTSTRAP/bin/go-9 build -o cmd/dist/dist ./cmd/dist
  
  eval `{./cmd/dist/dist env -9}
  if(~ $#vflag 1)
