update 2020-09-12 00:31

diff --git a/packages/c/combustion/combustion b/packages/c/combustion/combustion
--- a/packages/c/combustion/combustion
+++ b/packages/c/combustion/combustion
@@ -3,7 +3,39 @@
 # SPDX-License-Identifier: GPL-2.0-only
 set -euo pipefail
 
-config_mount="/mnt/combustion"
+config_mount="/run/combustion/mount"
+
+if [ "${1-}" = "--prepare" ]; then
+	# Mount config drive
+	mkdir -p "${config_mount}"
+
+	if ! [ -e /dev/disk/by-label/ignition ]; then
+		echo "No config drive found"
+		exit 0
+	fi
+
+	if ! mount -o ro /dev/disk/by-label/ignition "${config_mount}"; then
+		echo "Failed to mount config drive!"
+		exit 1
+	fi
+
+	# Check for the magic flag "# combustion: network" in the script
+	if [ -e "${config_mount}/combustion/script" ] \
+	   && grep -qE '^# combustion:(.*)\<network\>' "${config_mount}/combustion/script"; then
+		sh -s <<EOF
+			. /lib/dracut-lib.sh
+			getargbool 0 'rd.neednet' && exit 0
+			echo rd.neednet=1  > /etc/cmdline.d/40-combustion-neednet.conf
+			# Re-trigger generation of network rules and apply them
+			. /lib/dracut/hooks/pre-udev/60-net-genrules.sh
+			udevadm control --reload
+			udevadm trigger --subsystem-match net --action add
+EOF
+	fi
+
+	exit 0
+fi
+
 # Use /dev/shm for data exchange
 exchangedir="/dev/shm/combustion/"
 delete_resolv_conf=0
@@ -26,13 +58,6 @@ cleanup() {
 }
 
 trap cleanup EXIT
-
-# Mount config drive
-mkdir -p "${config_mount}"
-if ! mount -o ro /dev/disk/by-label/ignition "${config_mount}"; then
-	echo "Failed to mount config drive!"
-	exit 1
-fi
 
 if ! [ -d "${config_mount}/combustion" ]; then
 	echo "No config found - doing nothing."
