Update php-fpm8-image to rev 48 via SR 1373949
https://build.opensuse.org/request/show/1373949
by user pushman + anag_factory
🤖: sync package with devel:BCI:Tumbleweed from OBS

diff --git a/packages/p/php-fpm8-image/Dockerfile b/packages/p/php-fpm8-image/Dockerfile
--- a/packages/p/php-fpm8-image/Dockerfile
+++ b/packages/p/php-fpm8-image/Dockerfile
@@ -29,6 +29,32 @@ RUN set -euo pipefail; \
     export PERMCTL_ALLOW_INSECURE_MODE_IF_NO_PROC=1 SOURCE_DATE_EPOCH=0; \
     zypper -n --installroot /target --gpg-auto-import-keys install php8 php8-cli php-composer2 php8-curl php8-zip php8-zlib php8-phar php8-mbstring php8-fpm
 
+COPY docker-php-source docker-php-entrypoint docker-php-ext-configure docker-php-ext-enable docker-php-ext-install /target/usr/local/bin/
+RUN chmod +x /target/usr/local/bin/docker-php-*
+
+RUN set -euo pipefail; cd /target/etc/php8/fpm/; \
+test -e php-fpm.d/www.conf.default && cp -p php-fpm.d/www.conf.default php-fpm.d/www.conf; \
+test -e php-fpm.conf.default && cp -p php-fpm.conf.default php-fpm.conf; \
+{ \
+    echo '[global]'; \
+    echo 'error_log = /proc/self/fd/2'; \
+    echo; echo '; https://github.com/docker-library/php/pull/725#issuecomment-443540114'; echo 'log_limit = 8192'; \
+    echo; \
+    echo '[www]'; \
+    echo '; if we send this to /proc/self/fd/1, it never appears'; \
+    echo 'access.log = /proc/self/fd/2'; \
+    echo; \
+    echo 'clear_env = no'; \
+    echo; \
+    echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
+    echo 'catch_workers_output = yes'; \
+    echo 'decorate_workers_output = no'; \
+} | tee php-fpm.d/docker.conf; \
+{ \
+    echo '[global]'; \
+    echo 'daemonize = no'; \
+} | tee php-fpm.d/zz-docker.conf
+
 # cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n --installroot /target clean -a; \
     t=$(mktemp -d); mv /target/usr/lib/sysimage/rpm/Packages.db $t; rpmdb --rebuilddb --dbpath=$t; \
@@ -67,33 +93,8 @@ ENV PHP_INI_DIR="/etc/php8/"
 ENV PHP_VERSION="%%php_version%%"
 ENTRYPOINT ["docker-php-entrypoint"]
 CMD ["php-fpm"]
-COPY docker-php-source docker-php-entrypoint docker-php-ext-configure docker-php-ext-enable docker-php-ext-install /usr/local/bin/
-RUN chmod +x /usr/local/bin/docker-php-*
-WORKDIR /srv/www/htdocs
 
-RUN set -euo pipefail; \
-	cd /etc/php8/fpm/; \ 
-        test -e php-fpm.d/www.conf.default && cp -p php-fpm.d/www.conf.default php-fpm.d/www.conf; \
-        test -e php-fpm.conf.default && cp -p php-fpm.conf.default php-fpm.conf; \
-	{ \
-		echo '[global]'; \
-		echo 'error_log = /proc/self/fd/2'; \
-		echo; echo '; https://github.com/docker-library/php/pull/725#issuecomment-443540114'; echo 'log_limit = 8192'; \
-		echo; \
-		echo '[www]'; \
-		echo '; if we send this to /proc/self/fd/1, it never appears'; \
-		echo 'access.log = /proc/self/fd/2'; \
-		echo; \
-		echo 'clear_env = no'; \
-		echo; \
-		echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
-		echo 'catch_workers_output = yes'; \
-		echo 'decorate_workers_output = no'; \
-	} | tee php-fpm.d/docker.conf; \
-	{ \
-		echo '[global]'; \
-		echo 'daemonize = no'; \
-	} | tee php-fpm.d/zz-docker.conf
+WORKDIR /srv/www/htdocs
 
 # Override stop signal to stop process gracefully
 # https://github.com/php/php-src/blob/17baa87faddc2550def3ae7314236826bc1b1398/sapi/fpm/php-fpm.8.in#L163
