Update spamassassin to rev 86 via SR 917792
https://build.opensuse.org/request/show/917792
by user adkorte + dimstar_suse

diff --git a/packages/s/spamassassin/timed-sa-update b/packages/s/spamassassin/timed-sa-update
--- a/packages/s/spamassassin/timed-sa-update
+++ b/packages/s/spamassassin/timed-sa-update
@@ -13,31 +13,28 @@ then
 	. /etc/sysconfig/spamd
 fi
 
-if [ "$SPAM_SA_UPDATE" = "yes" ]
-then
-	/usr/bin/sa-update &> /dev/null
-	result=$?
+/usr/bin/sa-update &> /dev/null
+result=$?
 
-        if [ "$SPAM_SA_COMPILE" = "yes" -a $result = 0 ] ; then
-                /usr/bin/sa-compile &> /dev/null
-        fi
+if [ "$SPAM_SA_COMPILE" = "yes" -a $result = 0 ] ; then
+        /usr/bin/sa-compile &> /dev/null
+fi
 
-        if [ "$SPAM_SPAMD_RESTART" = "yes" -a $result = 0 ] ; then
-                /sbin/service spamd try-restart &> /dev/null
-        fi
+if [ "$SPAM_SPAMD_RESTART" = "yes" -a $result = 0 ] ; then
+        /sbin/service spamd try-restart &> /dev/null
+fi
 
-        if [ "$SPAM_AMAVISD_RESTART" = "yes" -a $result = 0 ] ; then
-                /sbin/service amavis try-restart &> /dev/null
-        fi
+if [ "$SPAM_AMAVISD_RESTART" = "yes" -a $result = 0 ] ; then
+        /sbin/service amavis try-restart &> /dev/null
+fi
 
-        if [ $result = 2 ] ; then
-               echo "sa-update lint check failed" | \
-                     logger -t timed-sa-update
-        fi
+if [ $result = 2 ] ; then
+       echo "sa-update lint check failed" | \
+             logger -t timed-sa-update
+fi
 
-        if [ $result -ge 3 ] ; then
-                echo "sa-update failed, exitcode $result" | \
-                     logger -t timed-sa-update
-        fi
+if [ $result -ge 3 ] ; then
+        echo "sa-update failed, exitcode $result" | \
+             logger -t timed-sa-update
 fi
 exit 0
