Update powerpc-utils to rev 100 via SR 779523
https://build.opensuse.org/request/show/779523
by user scarabeus_iv + dimstar_suse

diff --git a/packages/p/powerpc-utils/0001-powerpc-utils-Suppress-errors-reading-kernel-files.patch b/packages/p/powerpc-utils/0001-powerpc-utils-Suppress-errors-reading-kernel-files.patch
--- a/packages/p/powerpc-utils/0001-powerpc-utils-Suppress-errors-reading-kernel-files.patch
+++ b/packages/p/powerpc-utils/0001-powerpc-utils-Suppress-errors-reading-kernel-files.patch
@@ -34,19 +34,10 @@ Signed-off-by: Tyrel Datwyler <tyreld@linux.vnet.ibm.com>
  scripts/ofpathname | 4 ++--
  2 files changed, 6 insertions(+), 6 deletions(-)
 
-diff --git a/scripts/bootlist b/scripts/bootlist
-index acdaf89..1d1c210 100755
---- a/scripts/bootlist
-+++ b/scripts/bootlist
-@@ -169,7 +169,7 @@ get_logical_device_name()
-     local devname=$1
-     local logical_name
- 
--    logical_name=`$OFPATHNAME -l $devname 2>/dev/null`
-+    logical_name=`$OFPATHNAME -l $devname 2>/dev/null | tr -d '\000'`
-     if [[ $? -ne 0 ]]; then
- 	echo ""
-     else
+Index: powerpc-utils-1.3.7/scripts/bootlist
+===================================================================
+--- powerpc-utils-1.3.7.orig/scripts/bootlist
++++ powerpc-utils-1.3.7/scripts/bootlist
 @@ -207,11 +207,11 @@ show_bootlist()
      local devlist=$1
      local i
@@ -57,7 +48,7 @@ index acdaf89..1d1c210 100755
  	    name=`get_logical_device_name $i`
  	    if [[ -z $name ]]; then
 -	        echo "Could not translate $i to logical device name"
-+	        echo "Could not translate $i to logical device name" 2>&1
++	        echo "Could not translate $i to logical device name" >&2
  	    else
  		case $name in
  		    eth*)   parse_eth_info $name $i ;;
@@ -66,14 +57,14 @@ index acdaf89..1d1c210 100755
  . $PSERIES_PLATFORM
  if [[ $platform != $PLATFORM_PSERIES_LPAR ]]; then
 -    echo "bootlist: is not supported on the $platform_name platform"
-+    echo "bootlist: is not supported on the $platform_name platform" 2>&1
++    echo "bootlist: is not supported on the $platform_name platform" >&2
      exit 1
  fi
  
-diff --git a/scripts/ofpathname b/scripts/ofpathname
-index dc452c4..7c6345e 100755
---- a/scripts/ofpathname
-+++ b/scripts/ofpathname
+Index: powerpc-utils-1.3.7/scripts/ofpathname
+===================================================================
+--- powerpc-utils-1.3.7.orig/scripts/ofpathname
++++ powerpc-utils-1.3.7/scripts/ofpathname
 @@ -656,7 +656,7 @@ l2of_nvme()
  
          goto_dir $PWD "device/devspec"
@@ -92,6 +83,3 @@ index dc452c4..7c6345e 100755
      if [[ -z $devtype ]]; then
          err $ERR_NO_OFPATH
      fi
--- 
-2.16.4
-
