Update powerpc-utils to rev 102 via SR 808819
https://build.opensuse.org/request/show/808819
by user jmoellers + maxlin_factory

diff --git a/packages/p/powerpc-utils/0001-powerpc-utils-Suppress-errors-reading-kernel-files.patch b/packages/p/powerpc-utils/0001-powerpc-utils-Suppress-errors-reading-kernel-files.patch
--- a/packages/p/powerpc-utils/0001-powerpc-utils-Suppress-errors-reading-kernel-files.patch
+++ b/packages/p/powerpc-utils/0001-powerpc-utils-Suppress-errors-reading-kernel-files.patch
@@ -3,6 +3,10 @@ From: Michael Bringmann <mwb@linux.vnet.ibm.com>
 Date: Fri, 26 Jul 2019 09:10:51 -0500
 Subject: [PATCH] powerpc-utils: Suppress errors reading kernel files
 
+References: bsc#1116561 ltc#165182
+Upstream: pending - expected 1.3.8
+Git-commit: 73839d6bab4da24350a60105b7b2c3a6cc7d3a15
+
 A problem was observed with the evaluation of the '${devspec} by
 the script 'ofpathname'.  The problem occurred during installation
 to an nvme device as follows:
@@ -34,10 +38,19 @@ Signed-off-by: Tyrel Datwyler <tyreld@linux.vnet.ibm.com>
  scripts/ofpathname | 4 ++--
  2 files changed, 6 insertions(+), 6 deletions(-)
 
-Index: powerpc-utils-1.3.7/scripts/bootlist
-===================================================================
---- powerpc-utils-1.3.7.orig/scripts/bootlist
-+++ powerpc-utils-1.3.7/scripts/bootlist
+diff --git a/scripts/bootlist b/scripts/bootlist
+index acdaf8960ad0..1d1c210e69fc 100755
+--- a/scripts/bootlist
++++ b/scripts/bootlist
+@@ -169,7 +169,7 @@ get_logical_device_name()
+     local devname=$1
+     local logical_name
+ 
+-    logical_name=`$OFPATHNAME -l $devname 2>/dev/null`
++    logical_name=`$OFPATHNAME -l $devname 2>/dev/null | tr -d '\000'`
+     if [[ $? -ne 0 ]]; then
+ 	echo ""
+     else
 @@ -207,11 +207,11 @@ show_bootlist()
      local devlist=$1
      local i
@@ -48,7 +61,7 @@ Index: powerpc-utils-1.3.7/scripts/bootlist
  	    name=`get_logical_device_name $i`
  	    if [[ -z $name ]]; then
 -	        echo "Could not translate $i to logical device name"
-+	        echo "Could not translate $i to logical device name" >&2
++	        echo "Could not translate $i to logical device name" 2>&1
  	    else
  		case $name in
  		    eth*)   parse_eth_info $name $i ;;
@@ -57,14 +70,14 @@ Index: powerpc-utils-1.3.7/scripts/bootlist
  . $PSERIES_PLATFORM
  if [[ $platform != $PLATFORM_PSERIES_LPAR ]]; then
 -    echo "bootlist: is not supported on the $platform_name platform"
-+    echo "bootlist: is not supported on the $platform_name platform" >&2
++    echo "bootlist: is not supported on the $platform_name platform" 2>&1
      exit 1
  fi
  
-Index: powerpc-utils-1.3.7/scripts/ofpathname
-===================================================================
---- powerpc-utils-1.3.7.orig/scripts/ofpathname
-+++ powerpc-utils-1.3.7/scripts/ofpathname
+diff --git a/scripts/ofpathname b/scripts/ofpathname
+index dc452c4465ea..7c6345eeaca1 100755
+--- a/scripts/ofpathname
++++ b/scripts/ofpathname
 @@ -656,7 +656,7 @@ l2of_nvme()
  
          goto_dir $PWD "device/devspec"
@@ -83,3 +96,6 @@ Index: powerpc-utils-1.3.7/scripts/ofpathname
      if [[ -z $devtype ]]; then
          err $ERR_NO_OFPATH
      fi
+-- 
+2.26.2
+
