Update kubevirt-image to rev 4 via SR 1312602
https://build.opensuse.org/request/show/1312602
by user pushman + anag_factory
🤖: sync package with devel:BCI:Tumbleweed from OBS

diff --git a/packages/k/kubevirt-image/Dockerfile.exportproxy b/packages/k/kubevirt-image/Dockerfile.exportproxy
--- a/packages/k/kubevirt-image/Dockerfile.exportproxy
+++ b/packages/k/kubevirt-image/Dockerfile.exportproxy
@@ -34,6 +34,8 @@ RUN set -euo pipefail; \
     cut -d '.' -f -3)" = "1.6.2" ]
 RUN set -euo pipefail; useradd -u 1001 --create-home -s /bin/bash virt-exportproxy
 
+
+# cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n --installroot /target clean -a; \
     rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
     rm -rf {/target,}/run/*; \
@@ -42,6 +44,8 @@ RUN set -euo pipefail; zypper -n --installroot /target clean -a; \
     rm -f {/target,}/var/cache/ldconfig/aux-cache; \
     command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
 
+# set the day of last password change to empty
+RUN set -euo pipefail; sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/' /target/etc/shadow
 FROM opensuse/bci/bci-micro:latest
 COPY --from=builder /target /
 # Define labels according to https://en.opensuse.org/Building_derived_containers
