Update apache-tomcat-9-image to rev 25 via SR 1312594
https://build.opensuse.org/request/show/1312594
by user pushman + anag_factory
🤖: sync package with devel:BCI:Tumbleweed from OBS

diff --git a/packages/a/apache-tomcat-9-image/Dockerfile.openjdk17 b/packages/a/apache-tomcat-9-image/Dockerfile.openjdk17
--- a/packages/a/apache-tomcat-9-image/Dockerfile.openjdk17
+++ b/packages/a/apache-tomcat-9-image/Dockerfile.openjdk17
@@ -28,6 +28,8 @@ RUN set -euo pipefail; \
     export PERMCTL_ALLOW_INSECURE_MODE_IF_NO_PROC=1; \
     zypper -n --installroot /target --gpg-auto-import-keys install --no-recommends tomcat java-17-openjdk java-17-openjdk-headless; \
     zypper -n --installroot /target remove util-linux
+
+# cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n --installroot /target clean -a; \
     rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
     rm -rf {/target,}/run/*; \
@@ -36,6 +38,8 @@ RUN set -euo pipefail; zypper -n --installroot /target clean -a; \
     rm -f {/target,}/var/cache/ldconfig/aux-cache; \
     command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
 
+# set the day of last password change to empty
+RUN set -euo pipefail; sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/' /target/etc/shadow
 FROM opensuse/bci/bci-micro:latest
 COPY --from=builder /target /
 # Define labels according to https://en.opensuse.org/Building_derived_containers
