Update openjdk-17-image to rev 37 via SR 1312644
https://build.opensuse.org/request/show/1312644
by user pushman + anag_factory
🤖: sync package with devel:BCI:Tumbleweed from OBS

diff --git a/packages/o/openjdk-17-image/Dockerfile b/packages/o/openjdk-17-image/Dockerfile
--- a/packages/o/openjdk-17-image/Dockerfile
+++ b/packages/o/openjdk-17-image/Dockerfile
@@ -23,6 +23,8 @@ FROM opensuse/tumbleweed:latest
 
 RUN set -euo pipefail; \
     zypper -n install --no-recommends java-17-openjdk curl findutils gawk git-core procps util-linux
+
+# cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n clean -a; \
     rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
     rm -rf {/target,}/run/*; \
@@ -31,6 +33,8 @@ RUN set -euo pipefail; zypper -n clean -a; \
     rm -f {/target,}/var/cache/ldconfig/aux-cache; \
     command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
 
+# set the day of last password change to empty
+RUN set -euo pipefail; sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/' /etc/shadow
 
 # Define labels according to https://en.opensuse.org/Building_derived_containers
 # labelprefix=org.opensuse.bci.openjdk
