Update python-3.11-image to rev 40 via SR 1312607
https://build.opensuse.org/request/show/1312607
by user pushman + anag_factory
🤖: sync package with devel:BCI:Tumbleweed from OBS

diff --git a/packages/p/python-3.11-image/Dockerfile b/packages/p/python-3.11-image/Dockerfile
--- a/packages/p/python-3.11-image/Dockerfile
+++ b/packages/p/python-3.11-image/Dockerfile
@@ -24,6 +24,8 @@ FROM opensuse/tumbleweed:latest
 
 RUN set -euo pipefail; \
     zypper -n install --no-recommends python311-devel python311 python311-pip curl findutils gawk git-core procps util-linux python311-wheel python311-pipx
+
+# cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n clean -a; \
     rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
     rm -rf {/target,}/run/*; \
@@ -32,6 +34,8 @@ RUN set -euo pipefail; zypper -n clean -a; \
     rm -f {/target,}/var/cache/ldconfig/aux-cache; \
     command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
 
+# set the day of last password change to empty
+RUN set -euo pipefail; sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/' /etc/shadow
 
 # Define labels according to https://en.opensuse.org/Building_derived_containers
 # labelprefix=org.opensuse.bci.python
