Update micro-fips-image to version %OS_VERSION_ID_SP%.0.0 / rev 8 via SR 1312603
https://build.opensuse.org/request/show/1312603
by user pushman + anag_factory
🤖: sync package with devel:BCI:Tumbleweed from OBS

diff --git a/packages/m/micro-fips-image/Dockerfile b/packages/m/micro-fips-image/Dockerfile
--- a/packages/m/micro-fips-image/Dockerfile
+++ b/packages/m/micro-fips-image/Dockerfile
@@ -30,6 +30,8 @@ RUN set -euo pipefail; \
 
 RUN set -euo pipefail; zypper -n install jdupes \
     && jdupes -1 -L -r /target/usr/
+
+# cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n --installroot /target clean -a; \
     rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
     rm -rf {/target,}/run/*; \
@@ -38,6 +40,8 @@ RUN set -euo pipefail; zypper -n --installroot /target clean -a; \
     rm -f {/target,}/var/cache/ldconfig/aux-cache; \
     command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
 
+# set the day of last password change to empty
+RUN set -euo pipefail; sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/' /target/etc/shadow
 FROM scratch
 COPY --from=builder /target /
 # Define labels according to https://en.opensuse.org/Building_derived_containers
